SETUP:
#Sequential posts or random?
#e.g. would you like the posts to loop beginning-to-end in order,
#or would you like it to choose a post randomly each time and not use that
#post again until the list has run through?
#options are "sequential" or "random"
  TYPE: random
#The full path of the csv of the posts you want to make.
#I use my home folder but you do you. Must have read access.
#additionally, this can be a webpage. See "https://assets.jasonweiser.com/files/data/dune_quotes.csv"
#for an example of how to structure them. Or see the README.
  CSV_LOCATION: ""

TWITTER:
  ENABLE_TWITTER: False
  TWITTER_CONSUMER_KEY: ""
  TWITTER_CONSUMER_SECRET: ""
  TWITTER_ACCESS_TOKEN: ""
  TWITTER_ACCESS_TOKEN_SECRET: ""
  ENABLE_HASHTAGS: False
  HASHTAGS: ["Hashtag","Hashtag"]

MASTODON:
  ENABLE_MASTODON: False
  MASTODON_ACCESS_TOKEN: ""
  MASTO_BASE_URL: ""
  ENABLE_HASHTAGS: False
  HASHTAGS: ["Hashtag","Hashtag"]